# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{wordchuck}
  s.version = "0.0.14"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shelly Roche"]
  s.date = %q{2010-11-26}
  s.description = %q{gem for the Wordchuck website translation service for locale file generation}
  s.email = %q{shelly@wordchuck.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/tasks/generate.rake",
     "lib/wordchuck.rb",
     "lib/wordchuck/chucker.rb",
     "lib/wordchuck/client.rb",
     "lib/wordchuck/configuration.rb",
     "lib/wordchuck/railtie.rb",
     "test/helper.rb",
     "test/test_locales.rb",
     "test/test_selections.rb"
  ]
  s.homepage = %q{http://github.com/shellyroche/wordchuck}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{wordchuck}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{gem for the Wordchuck website translation service}
  s.test_files = [
    "test/helper.rb",
     "test/test_locales.rb",
     "test/test_selections.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.6.0"])
      s.add_runtime_dependency(%q<json_pure>, [">= 1.4.4"])
      s.add_runtime_dependency(%q<human_hash>, [">= 0.2.1"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<rest-client>, ["~> 1.6.0"])
      s.add_dependency(%q<json_pure>, [">= 1.4.4"])
      s.add_dependency(%q<human_hash>, [">= 0.2.1"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<rest-client>, ["~> 1.6.0"])
    s.add_dependency(%q<json_pure>, [">= 1.4.4"])
    s.add_dependency(%q<human_hash>, [">= 0.2.1"])
  end
end

